### ISSUE TITLE
 Could not find module 'geos_c.dll'

### ISSUE THREAD

**Issue by Muhammad-Waqas5012** [greppo-io/greppo#40]
"Collecting Shapely==1.7.1
  Using cached Shapely-1.7.1.tar.gz (383 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\waqas\AppData\Local\Temp\pip-install-tejpkfb2\shapely_c15553460ad04164b9fc4f0138c13331\setup.py", line 85
, in <module>
          from shapely._buildcfg import geos_version_string, geos_version, \
        File "C:\Users\waqas\AppData\Local\Temp\pip-install-tejpkfb2\shapely_c15553460ad04164b9fc4f0138c13331\shapely\_buildcfg.
py", line 205, in <module>
          lgeos = CDLL("geos_c.dll")
        File "C:\Users\waqas\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
          self._handle = _dlopen(self._name, mode)
      FileNotFoundError: Could not find module 'geos_c.dll' (or one of its dependencies). Try using the full path with construct
or syntax.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

"
"
This error is coming how to resolve it
"

**Comment by krish-adi** [comment]
It looks like you are using Python 3.10. Could you use 3.9 and check?

Greppo and its dependencies currently don't Python version 3.10.
