### ISSUE TITLE
Installation error collecting shapely metadata-generation-failed

### ISSUE THREAD

**Issue by mathiasschlaeffer** [greppo-io/greppo#61]
I followed the installation described here: https://docs.greppo.io/installation.html
yet when running pip install greppo it seems that collecting shapely is not possible:

Collecting Shapely==1.7.1 (from greppo)
  Using cached Shapely-1.7.1.tar.gz (383 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

Is the installation advice still valid?

**Comment by krish-adi** [comment]
Are you running on Windows? Which Python version are you using?

**Comment by MauricioRojasCareers** [comment]
I am running Windows 10 and have Python 3.11.4 latest fresh install. I am also running in to the same issue, what python version would you recommend?

**Comment by MauricioRojasCareers** [comment]
``(ENV) PS C:\Users\mroja\✰Legacy✰\python\_sandbox\greppo-example> pip install greppo
Collecting greppo
  Using cached greppo-0.0.33-py3-none-any.whl (1.7 MB)
Collecting click==8.0.3 (from greppo)
  Using cached click-8.0.3-py3-none-any.whl (97 kB)
Collecting geopandas>=0.9.0 (from greppo)
  Obtaining dependency information for geopandas>=0.9.0 from https://files.pythonhosted.org/packages/cb/7b/2fb6ab376c78d2e60812ad0bf4b24889309d2aeb543f54efcd586c69907f/geopandas-0.13.2-py3-none-any.whl.metadata
  Using cached geopandas-0.13.2-py3-none-any.whl.metadata (1.5 kB)
Collecting pandas>=1.1.5 (from greppo)
  Obtaining dependency information for pandas>=1.1.5 from https://files.pythonhosted.org/packages/9e/71/756a1be6bee0209d8c0d8c5e3b9fc72c00373f384a4017095ec404aec3ad/pandas-2.0.3-cp311-cp311-win_amd64.whl.metadata
  Using cached pandas-2.0.3-cp311-cp311-win_amd64.whl.metadata (18 kB)
Collecting numpy (from greppo)
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/72/b2/02770e60c4e2f7e158d923ab0dea4e9f146a2dbf267fec6d8dc61d475689/numpy-1.25.2-cp311-cp311-win_amd64.whl.metadata
  Using cached numpy-1.25.2-cp311-cp311-win_amd64.whl.metadata (5.7 kB)
Collecting Shapely==1.7.1 (from greppo)
  Using cached Shapely-1.7.1.tar.gz (383 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\mroja\AppData\Local\Temp\pip-install-kfy4_8r8\shapely_0249070328ed4f5db76014f6c5f3e48d\setup.py", line 85, in <module>
          from shapely._buildcfg import geos_version_string, geos_version, \
        File "C:\Users\mroja\AppData\Local\Temp\pip-install-kfy4_8r8\shapely_0249070328ed4f5db76014f6c5f3e48d\shapely\_buildcfg.py", line 205, in <module>
          lgeos = CDLL("geos_c.dll")
                  ^^^^^^^^^^^^^^^^^^
        File "C:\Users\mroja\.pyenv\pyenv-win\versions\3.11.4\Lib\ctypes\__init__.py", line 376, in __init__
          self._handle = _dlopen(self._name, mode)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: Could not find module 'geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.``

**Comment by MauricioRojasCareers** [comment]
exact error ^
